name=LCP_sliderPz
version=1.0.0
author=jim lee
maintainer=sliderPz@leftcoast.biz
sentence=A version of the sliding 2D puzzle game. Runs under lilOS.
paragraph=It's a puzzle that you slide picture pieces around in a frame until you find their order. Then you can see the picture. Runs on an Arduino running under lilOS.
category=Other
url=https://github.com/leftCoast/LCP_sliderPz
architectures=*
depends=LC_lilOS
dot_a_linkage=true
